"""Create core models

Revision ID: 220c5341cda6
Revises: 0001
Create Date: 2026-05-08 00:46:49.101568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '220c5341cda6'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('PLAN_CREATED', 'DEADLINE_CHANGED', 'STATUS_CHANGED', 'APPROVAL_REQUESTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', 'EXTERNAL_LINK_ADDED', 'EXTERNAL_LINK_REMOVED', 'PLAN_ITEM_DELETED', name='event_type'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_log_actor_created', 'event_log', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_event_log_actor_id'), 'event_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_event_log_created_at'), 'event_log', ['created_at'], unique=False)
    op.create_index('ix_event_log_entity', 'event_log', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_event_log_entity_id'), 'event_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_log_entity_type'), 'event_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_table('organization_unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('DEPARTMENT', 'TEAM', name='organization_level'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_unit.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organization_unit_is_active', 'organization_unit', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_organization_unit_level'), 'organization_unit', ['level'], unique=False)
    op.create_index(op.f('ix_organization_unit_parent_id'), 'organization_unit', ['parent_id'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('organization_unit_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'MEMBER', name='employee_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_unit.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=False)
    op.create_index('ix_employee_is_active', 'employee', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_employee_organization_unit_id'), 'employee', ['organization_unit_id'], unique=False)
    op.create_table('plan_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('MONTH', 'WEEK', 'DAY', name='plan_item_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='plan_status'), nullable=False),
    sa.Column('responsible_employee_id', sa.Integer(), nullable=False),
    sa.Column('organization_unit_id', sa.Integer(), nullable=False),
    sa.Column('original_start_date', sa.Date(), nullable=True),
    sa.Column('original_end_date', sa.Date(), nullable=True),
    sa.Column('current_start_date', sa.Date(), nullable=True),
    sa.Column('current_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_unit.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employee.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_item_current_end_date'), 'plan_item', ['current_end_date'], unique=False)
    op.create_index(op.f('ix_plan_item_current_start_date'), 'plan_item', ['current_start_date'], unique=False)
    op.create_index(op.f('ix_plan_item_organization_unit_id'), 'plan_item', ['organization_unit_id'], unique=False)
    op.create_index(op.f('ix_plan_item_original_end_date'), 'plan_item', ['original_end_date'], unique=False)
    op.create_index(op.f('ix_plan_item_original_start_date'), 'plan_item', ['original_start_date'], unique=False)
    op.create_index(op.f('ix_plan_item_responsible_employee_id'), 'plan_item', ['responsible_employee_id'], unique=False)
    op.create_index(op.f('ix_plan_item_status'), 'plan_item', ['status'], unique=False)
    op.create_index(op.f('ix_plan_item_type'), 'plan_item', ['type'], unique=False)
    op.create_index('ix_plan_item_type_status', 'plan_item', ['type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plan_item_type_status', table_name='plan_item')
    op.drop_index(op.f('ix_plan_item_type'), table_name='plan_item')
    op.drop_index(op.f('ix_plan_item_status'), table_name='plan_item')
    op.drop_index(op.f('ix_plan_item_responsible_employee_id'), table_name='plan_item')
    op.drop_index(op.f('ix_plan_item_original_start_date'), table_name='plan_item')
    op.drop_index(op.f('ix_plan_item_original_end_date'), table_name='plan_item')
    op.drop_index(op.f('ix_plan_item_organization_unit_id'), table_name='plan_item')
    op.drop_index(op.f('ix_plan_item_current_start_date'), table_name='plan_item')
    op.drop_index(op.f('ix_plan_item_current_end_date'), table_name='plan_item')
    op.drop_table('plan_item')
    op.drop_index(op.f('ix_employee_organization_unit_id'), table_name='employee')
    op.drop_index('ix_employee_is_active', table_name='employee', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_organization_unit_parent_id'), table_name='organization_unit')
    op.drop_index(op.f('ix_organization_unit_level'), table_name='organization_unit')
    op.drop_index('ix_organization_unit_is_active', table_name='organization_unit', postgresql_where=sa.text('is_active = true'))
    op.drop_table('organization_unit')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_entity_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_entity_id'), table_name='event_log')
    op.drop_index('ix_event_log_entity', table_name='event_log')
    op.drop_index(op.f('ix_event_log_created_at'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_actor_id'), table_name='event_log')
    op.drop_index('ix_event_log_actor_created', table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###
