"""Make responsible_employee_id and organization_unit_id nullable

Revision ID: 2a3b4c5d6e7f
Revises: 220c5341cda6
Create Date: 2026-05-08 10:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2a3b4c5d6e7f"
down_revision: Union[str, None] = "220c5341cda6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan_item",
        "responsible_employee_id",
        existing_type=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "plan_item",
        "organization_unit_id",
        existing_type=sa.Integer(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: Downgrade will fail if any rows have NULL values in these columns.
    op.alter_column(
        "plan_item",
        "responsible_employee_id",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.alter_column(
        "plan_item",
        "organization_unit_id",
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###
