"""Add PlanLink model

Revision ID: 9aec91f4138c
Revises: 2a3b4c5d6e7f
Create Date: 2026-05-08 12:39:13.640251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aec91f4138c'
down_revision: Union[str, None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# New values added to existing event_type enum
_new_event_types = (
    "link_created",
    "link_deactivated",
    "link_activated",
    "link_deleted",
)


def upgrade() -> None:
    # Add new values to existing event_type enum
    # PostgreSQL does not support adding multiple values in one ALTER TYPE,
    # so we use a batch operation
    for event_type in _new_event_types:
        op.execute(
            sa.text(
                f"ALTER TYPE event_type ADD VALUE IF NOT EXISTS '{event_type}'"
            )
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_plan_item_id', sa.Integer(), nullable=True),
    sa.Column('target_plan_item_id', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.Enum('PARENT_CHILD', 'RELATED', 'DEPENDS_ON', 'BLOCKS', name='plan_link_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_plan_item_id'], ['plan_item.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_plan_item_id'], ['plan_item.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_plan_item_id', 'target_plan_item_id', 'link_type', name='uq_plan_link_source_target_type')
    )
    op.create_index('ix_plan_link_is_active', 'plan_link', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_plan_link_link_type'), 'plan_link', ['link_type'], unique=False)
    op.create_index(op.f('ix_plan_link_source_plan_item_id'), 'plan_link', ['source_plan_item_id'], unique=False)
    op.create_index('ix_plan_link_source_type', 'plan_link', ['source_plan_item_id', 'link_type'], unique=False)
    op.create_index(op.f('ix_plan_link_target_plan_item_id'), 'plan_link', ['target_plan_item_id'], unique=False)
    op.create_index('ix_plan_link_target_type', 'plan_link', ['target_plan_item_id', 'link_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plan_link_target_type', table_name='plan_link')
    op.drop_index(op.f('ix_plan_link_target_plan_item_id'), table_name='plan_link')
    op.drop_index('ix_plan_link_source_type', table_name='plan_link')
    op.drop_index(op.f('ix_plan_link_source_plan_item_id'), table_name='plan_link')
    op.drop_index(op.f('ix_plan_link_link_type'), table_name='plan_link')
    op.drop_index('ix_plan_link_is_active', table_name='plan_link', postgresql_where=sa.text('is_active = true'))
    op.drop_table('plan_link')
    op.execute(sa.text("DROP TYPE IF EXISTS plan_link_type"))
    # ### end Alembic commands ###

    # Note: PostgreSQL does not support removing values from an enum.
    # The new event_type values (link_*) will remain in the enum type
    # even after downgrade. This is an accepted PostgreSQL limitation.
