"""add_approval_model

Revision ID: b1f75773e6a3
Revises: 9aec91f4138c
Create Date: 2026-05-26 23:08:23.142858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f75773e6a3'
down_revision: Union[str, None] = '9aec91f4138c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_item_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('new_start_date', sa.Date(), nullable=True),
    sa.Column('new_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_plan_item_id'), 'approval', ['plan_item_id'], unique=False)
    op.create_index(op.f('ix_approval_requested_by_id'), 'approval', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_approval_reviewed_by_id'), 'approval', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_approval_status'), 'approval', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_status'), table_name='approval')
    op.drop_index(op.f('ix_approval_reviewed_by_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_requested_by_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_plan_item_id'), table_name='approval')
    op.drop_table('approval')
    # ### end Alembic commands ###
